FROM openjdk:8u262-jre-slim-buster
ADD service/service_users/target/service_users-0.0.1-SNAPSHOT.jar /backend-users/backend-users.jar
ADD runboot-user.sh /backend-users/
WORKDIR /backend-users
RUN chmod a+x runboot-user.sh
CMD /backend-users/runboot-user.sh